# Generated by Django 4.2.7 on 2026-01-16 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalstate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotional_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
